Bypass logscale=True of matplotlib.pyplot
- The logscale=True of matplotlib.pyplot does not work!
- It throws an error:
  ValueError: Data has no positive values, and therefore can not be log-scaled.                                                                                           - There is no negative or zero in the data. It only works if eke>1000 (cm/s)^2 !
- It used to work before !
- So, for now just pass the log of eke to pyplot